{
  "openapi":"3.0.2",
  "info": {
    "title":"Aircnc",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/aircnc-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["Sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "johndoe@example.com"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticates user, return a Bearer Token and user's email",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "title": "User",
                      "allOf": [
                        {
                          "title": "User",
                          "properties": {
                            "_id": {
                              "type": "string"
                            }
                          }
                        },
                        {
                          "$ref": "#/components/schemas/User"
                        }
                      ]
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "user": {
                    "_id": "6137edecf1247f5bd4c2b396",
                    "email": "johndoe@gmail.com"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzdlZGVjZjEyNDdmNWJkNGMyYjM5NiIsImlhdCI6MTYzMTA1NTM0MCwiZXhwIjoxNjMxNjYwMTQwfQ.JqqKpS2LBEq79AV3inDtJ3q3j7ir7wzi_m5O15WZGHY"
                }
              }
            }
          }
        }
      }
    },
    "/spots": {
      "get": {
        "tags": ["Spots"],
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "tech",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "Node.js"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists available spots by tech",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Spot"
                      },
                      {
                        "title": "Spot",
                        "properties": {
                          "url": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "_id": "6137f5caabb1fd6124a75fe9",
                    "techs": [
                      "Node.js",
                      "ReactJS",
                      "ReactNative"
                    ],
                    "user": "6137edecf1247f5bd4c2b396",
                    "company": "Blockcode",
                    "price": 89,
                    "thumbnail": "example-1631057354938.jpg",
                    "thumbnail_url": "http://localhost:3333/files/example-1631057354938.jpg",
                    "url": "http://localhost:3333/v1/spots/6137eff508f80d2f6488af54"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "$ref": "#/components/headers/X-Total-Count"
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Spots"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "company",
                  "price",
                  "techs",
                  "thumbnail"
                ],
                "properties": {
                  "company": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  },
                  "techs": {
                    "type": "string"
                  },
                  "thumbnail": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new spot",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Spot"
                },
                "example": {
                  "_id": "6137f5caabb1fd6124a75fe9",
                  "techs": [
                    "Node.js",
                    "ReactJS",
                    "ReactNative"
                  ],
                  "user": "6137edecf1247f5bd4c2b396",
                  "company": "Blockcode",
                  "price": 90,
                  "thumbnail": "example-1631057354938.jpg",
                  "thumbnail_url": "http://127.0.0.1:3333/files/example-1631057354938.jpg"
                }
              }
            }
          },
          "404": {
            "description": "User does not exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "User does not exists",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/aircnc-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/spots/{id}": {
      "get": {
        "tags": ["Spots"],
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "responses": {
          "200": {
            "description": "Return one spot",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Spot"
                    },
                    {
                      "title": "Spot",
                      "properties": {
                        "bookings": {
                          "type": "array",
                          "items": {
                            "title": "Booking",
                            "properties": {
                              "_id": {
                                "type": "string"
                              },
                              "user": {
                                "type": "object",
                                "allOf": [
                                  {
                                    "title": "User",
                                    "properties": {
                                      "_id": {
                                        "type": "string"
                                      }
                                    }
                                  },
                                  {
                                    "$ref": "#/components/schemas/User"
                                  }
                                ]
                              },
                              "spot": {
                                "type": "string"
                              },
                              "date": {
                                "type": "string"
                              },
                              "approved": {
                                "type": "boolean"
                              }
                            }
                          }
                        },
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "_id": "6137eff508f80d2f6488af54",
                  "techs": [
                    "Node.js",
                    "ReactJS",
                    "ReactNative"
                  ],
                  "user": "6137eff208f80d2f6488af51",
                  "company": "Blockcode",
                  "price": 89,
                  "thumbnail": "example-1631055861917.jpg",
                  "thumbnail_url": "http://127.0.0.1:3333/files/example-1631055861917.jpg",
                  "bookings": [
                    {
                      "_id": "6137f22159b70c5da4feac05",
                      "user": {
                        "_id": "6137eff208f80d2f6488af51",
                        "email": "johndoe@example.com"
                      },
                      "spot": "6137eff508f80d2f6488af54",
                      "date": "2021-11-02T02:16:52.000Z",
                      "approved": true
                    }
                  ],
                  "url": "http://localhost:3333/v1/spots/6137eff508f80d2f6488af54"
                }
              }
            },
            "headers": {
              "X-Total-Count": {
                "$ref": "#/components/headers/X-Total-Count"
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Spots"],
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "company": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  },
                  "techs": {
                    "type": "string"
                  },
                  "thumbnail": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              },
              "example": {
                "techs": "Node.js, ReactNative"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Create a new spot",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Spot"
                    },
                    {
                      "properties": {
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "_id": "6137f76155738c65304a4feb",
                  "techs": [
                    "Node.js",
                    "ReactJS",
                    "ReactNative"
                  ],
                  "user": "6137edecf1247f5bd4c2b396",
                  "company": "Blockcode",
                  "price": 90,
                  "thumbnail": "example-1631057761137.jpg",
                  "thumbnail_url": "http://127.0.0.1:3333/files/example-1631057761137.jpg",
                  "url": "http://localhost:3333/v1/spots/6137f76155738c65304a4feb"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Spots"],
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "responses": {
          "204": {
            "description": "Return one spot"
          },
          "401": {
            "description": "You can not remove spot with bookings approved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "example": {
                  "statusCode": 401,
                  "error": "Unauthorized",
                  "message": "You can not remove spot with bookings approved",
                  "attributes": {
                    "code": 341,
                    "error": "You can not remove spot with bookings approved"
                  },
                  "docs": "https://github.com/DiegoVictor/aircnc-api#errors-reference"
                }
              }
            }
          },
          "404": {
            "description": "Spot not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Spot does not exists",
                  "code": 344,
                  "docs": "https://github.com/DiegoVictor/aircnc-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
  },
  "components": {
    "schemas": {
      "User": {
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string"
          }
        }
      },
      "Booking": {
        "properties": {
          "_id": {
            "type": "string"
          },
          "user": {
            "type": "object",
            "allOf": [
              {
                "title": "User",
                "properties": {
                  "_id": {
                    "type": "string"
                  }
                }
              },
              {
                "$ref": "#/components/schemas/User"
              }
            ]
          },
          "spot": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Spot"
              },
              {
                "properties": {
                  "url": {
                    "type": "string"
                  }
                }
              }
            ]
          },
          "approved": {
            "type": "boolean"
          },
          "date": {
            "type": "string"
          }
        }
      },
      "Spot": {
        "properties": {
          "_id": {
            "type": "string"
          },
          "techs": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "user": {
            "type": "string"
          },
          "company": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "thumbnail": {
            "type": "string"
          },
          "thumbnail_url": {
            "type": "string"
          }
        }
      },
      "Unauthorized": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer"
              },
              "error": {
                "type": "string"
              }
            }
          },
          "docs": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "booking": {
        "value": {
          "_id": "613804ba610cf66ad8e75cd0",
          "user": {
            "_id": "613803f4d36ba4650ca01b86",
            "email": "johndoe@example.com"
          },
          "spot": {
            "_id": "613803f6d36ba4650ca01b89",
            "techs": [
              "Node.js"
            ],
            "user": "613803f4d36ba4650ca01b86",
            "company": "Rocketseat",
            "price": 89,
            "thumbnail": "example-1631060982759.jpg",
            "thumbnail_url": "http://127.0.0.1:3333/files/example-1631060982759.jpg",
            "url": "http://localhost:3333/v1/spots/613803f6d36ba4650ca01b89"
          },
          "date": "2021-11-02T02:16:52.000Z"
        }
      },
      "bookings": {
        "value": {
          "_id": "613804ba610cf66ad8e75cd0",
          "user": {
            "_id": "613803f4d36ba4650ca01b86",
            "email": "johndoe@example.com"
          },
          "spot": {
            "_id": "613803f6d36ba4650ca01b89",
            "techs": [
              "Node.js"
            ],
            "user": "613803f4d36ba4650ca01b86",
            "company": "Rocketseat",
            "price": 89,
            "thumbnail": "example-1631060982759.jpg",
            "thumbnail_url": "http://127.0.0.1:3333/files/example-1631060982759.jpg",
            "url": "http://localhost:3333/v1/spots/613803f6d36ba4650ca01b89"
          },
          "date": "2021-11-02T02:16:52.000Z"
        }
      }
    },
    "parameters": {
      "id": {
        "in": "path",
        "name": "id",
        "required": true,
        "schema": {
          "type": "string"
        },
        "example": "613804ba610cf66ad8e75cd0"
      }
    },
    "headers": {
      "X-Total-Count": {
        "description": "Total number of registries in the database",
        "schema": {
          "type": "integer"
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "scheme": "bearer",
        "type": "http"
      }
    }
  }
}
